# Generated by Django 2.2.4 on 2026-06-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='地点名称')),
                ('category', models.CharField(choices=[('city', '城市探险'), ('alley', '巷弄巡逻'), ('forest', '森林探险')], max_length=10, verbose_name='分类')),
                ('slug', models.SlugField(unique=True, verbose_name='URL标识')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='纬度')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='经度')),
                ('address', models.CharField(max_length=255, verbose_name='详细地址')),
                ('image', models.ImageField(upload_to='spots/', verbose_name='地点图片')),
                ('description', models.TextField(verbose_name='地点简介')),
                ('mood_tag', models.CharField(max_length=50, verbose_name='心情标签')),
                ('meow_rate', models.IntegerField(default=0, verbose_name='猫咪出没率(%)')),
                ('cost_desc', models.CharField(max_length=50, verbose_name='费用说明')),
                ('time_required', models.CharField(max_length=50, verbose_name='建议耗时')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否首页推荐')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '探险地点',
                'verbose_name_plural': '探险地点',
            },
        ),
    ]
