# Generated by Django 2.2.4 on 2026-06-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('route', '秘境路线'), ('camping', '躲猫猫营地')], max_length=10, null=True, verbose_name='森林版块'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='cost_desc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='费用说明'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='mood_tag',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='心情标签'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='time_required',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='建议耗时'),
        ),
    ]
