# Generated by Django 2.2.4 on 2026-06-05 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapApp', '0002_auto_20260602_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='collect_count',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AddField(
            model_name='spot',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.CreateModel(
            name='SpotCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='mapApp.Spot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '景点收藏',
                'verbose_name_plural': '景点收藏',
                'unique_together': {('spot', 'user')},
            },
        ),
    ]
