# Generated by Django 2.2.4 on 2026-06-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0003_auto_20260605_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForestBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='喵友昵称')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('destination', models.CharField(max_length=200, verbose_name='选择目的地')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '森林预约',
                'verbose_name_plural': '森林预约',
                'ordering': ['-created_at'],
            },
        ),
    ]
