# Generated by Django 2.2.4 on 2026-06-04 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='活动类别')),
                ('badge_color', models.CharField(default='#FF9F89', max_length=20, verbose_name='标签颜色')),
            ],
            options={
                'verbose_name': '活动分类',
                'verbose_name_plural': '活动分类',
            },
        ),
        migrations.CreateModel(
            name='StoreShelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='货架名称')),
                ('order', models.IntegerField(default=0, verbose_name='排序权重')),
            ],
            options={
                'verbose_name': '货架分类',
                'verbose_name_plural': '货架分类',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('image', models.ImageField(upload_to='store/', verbose_name='商品图')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('description', models.TextField(verbose_name='商品简介')),
                ('purchase_guide', models.TextField(blank=True, verbose_name='购买指南/备注')),
                ('link', models.URLField(verbose_name='购买链接')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shopApp.StoreShelf', verbose_name='所属货架')),
            ],
            options={
                'verbose_name': '周边商品',
                'verbose_name_plural': '周边商品',
            },
        ),
        migrations.CreateModel(
            name='ActivityItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='活动名称')),
                ('cover_image', models.ImageField(upload_to='activity/', verbose_name='封面图')),
                ('duration', models.CharField(max_length=50, verbose_name='耗时')),
                ('location', models.CharField(max_length=200, verbose_name='地点')),
                ('description', models.TextField(verbose_name='活动简介')),
                ('services', models.CharField(max_length=500, verbose_name='活动包含(用逗号隔开)')),
                ('booking_link', models.URLField(verbose_name='预订链接')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='shopApp.ActivityCategory', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '特色活动',
                'verbose_name_plural': '特色活动',
            },
        ),
    ]
