# Generated by Django 2.2.4 on 2026-06-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycategory',
            name='badge_color',
            field=models.CharField(choices=[('#FF9F89', '元气珊瑚粉 (活动特色)'), ('#A7C4BC', '清新薄荷绿 (自然/环保)'), ('#4A4E69', '沉稳暗夜蓝 (人文/考古)'), ('#FFC857', '活力明黄 (探险/任务)'), ('#E9C46A', '复古奶咖 (手作/文化)'), ('#2A9D8F', '森林深绿 (户外/徒步)'), ('#E76F51', '暖阳陶土红 (艺术/民俗)'), ('#8D99AE', '静谧灰蓝 (研学/科普)')], default='#FF9F89', max_length=20, verbose_name='标签背景色'),
        ),
    ]
