# Generated by Django 2.2.4 on 2026-06-05 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='相册标题')),
                ('description', models.TextField(blank=True, verbose_name='相册描述')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='albums/covers/', verbose_name='相册封面')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '个人相册',
                'verbose_name_plural': '个人相册',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='照片标题')),
                ('image', models.ImageField(upload_to='albums/photos/', verbose_name='照片文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='accountApp.Album', verbose_name='所属相册')),
            ],
            options={
                'verbose_name': '相册照片',
                'verbose_name_plural': '相册照片',
                'ordering': ['-created_at'],
            },
        ),
    ]
