# Generated by Django 2.2.4 on 2026-06-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default_cat_avatar.jpg', null=True, upload_to='avatar/'),
        ),
    ]
