# Generated by Django 2.2.4 on 2026-06-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notecollection',
            options={'verbose_name': '游记收藏', 'verbose_name_plural': '游记收藏'},
        ),
        migrations.AlterModelOptions(
            name='notecomment',
            options={'verbose_name': '游记评论', 'verbose_name_plural': '游记评论'},
        ),
        migrations.AlterModelOptions(
            name='notelike',
            options={'verbose_name': '游记点赞', 'verbose_name_plural': '游记点赞'},
        ),
        migrations.AlterField(
            model_name='note',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='notes/covers/', verbose_name='封面图'),
        ),
    ]
