# Generated by Django 2.2.4 on 2026-05-29 03:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('bug', 'BUG反馈（抓个虫）'), ('suggest', '功能建议（添块砖）'), ('error', '路线纠错（迷路啦）'), ('other', '其他想说的话')], max_length=20, verbose_name='信件类型')),
                ('nickname', models.CharField(max_length=50, verbose_name='喵友昵称')),
                ('email', models.EmailField(max_length=254, verbose_name='回信邮箱')),
                ('content', models.TextField(verbose_name='信件内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投递时间')),
                ('is_processed', models.BooleanField(default=False, verbose_name='喵喵是否处理/回复')),
            ],
            options={
                'verbose_name': '喵喵信箱',
                'verbose_name_plural': '喵喵信箱',
                'ordering': ['-created_at'],
            },
        ),
    ]
