# Generated by Django 2.2.4 on 2026-06-02 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='相册名称')),
                ('cover_image', models.ImageField(upload_to='diary/covers/', verbose_name='相册封面')),
                ('description', models.TextField(blank=True, verbose_name='相册简介')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '追光日记相册',
                'verbose_name_plural': '追光日记相册',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='照片标题')),
                ('image', models.ImageField(upload_to='diary/photos/', verbose_name='日记照片')),
                ('latitude', models.CharField(help_text='例如: 30.60°N', max_length=20, verbose_name='纬度')),
                ('longitude', models.CharField(help_text='例如: 119.86°E', max_length=20, verbose_name='经度')),
                ('shutter_speed', models.CharField(help_text='例如: 1/125s', max_length=20, verbose_name='快门速度')),
                ('aperture', models.CharField(help_text='例如: f/2.8', max_length=20, verbose_name='光圈')),
                ('iso', models.IntegerField(verbose_name='ISO感光度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='newsApp.DiaryAlbum', verbose_name='所属相册')),
            ],
            options={
                'verbose_name': '拍立得照片',
                'verbose_name_plural': '拍立得照片',
            },
        ),
    ]
