# Generated by Django 2.2.4 on 2026-06-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='aperture',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='光圈'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='iso',
            field=models.IntegerField(blank=True, null=True, verbose_name='ISO感光度'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='shutter_speed',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='快门速度'),
        ),
    ]
