# Generated by Django 2.2.4 on 2026-06-02 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0002_auto_20260603_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='板块标题')),
                ('tag', models.CharField(max_length=50, verbose_name='标签')),
            ],
            options={
                'verbose_name': '新闻板块',
                'verbose_name_plural': '新闻板块',
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='资讯内容')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热门(HOT)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='newsApp.NewsCategory', verbose_name='所属板块')),
            ],
            options={
                'verbose_name': '鱼干资讯',
                'verbose_name_plural': '鱼干资讯',
            },
        ),
    ]
